### ISSUE TITLE
Define gameplay

### ISSUE THREAD

**Issue by fabric-and-ink** [K4ugummi/carambolage#4]
The first idea is to make a multi player game of catch-me with little cars. On player is "it" and this player has to bump into another car to transfer being "it" to the other car. One round finishes after a certain time and the player who is "it" is out.

cc @K4ugummi

**Comment by K4ugummi** [comment]
- [ ]  Playing Catch:
> The first idea is to make a multi player game of catch-me with little cars. On player is "it" and this player has to bump into another car to transfer being "it" to the other car. One round finishes after a certain time and the player who is "it" is out.
- [ ]  Race Mode:
> Users have to race around a course. The camera focuses on the leading car. If others fall behind too far, they lose. Winner is the last car or first to cross the finish line.
- [ ] Lawn mower tractor:
> Drift around different maps and try to to mow ~90% of the green as fast as possible. Avoid flowers and other stuff to not get penalty time.
